### ISSUE TITLE
Failed to authenticate user on kubernetes environment

### ISSUE THREAD

**Issue by ericbaum** [dojot/auth#3]
On the mongo database, if the user item doesn't have a tokenExpiration field the auth returns the following error:

```
[2017-10-05 19:25:55,018] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/Flask-0.12-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/auth/app.py", line 73, in authenticate
    'exp': int(time.time() + tokenExpiration),
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
XX.XX.XX.XX - - [05/Oct/2017:19:25:55 +0000] "POST / HTTP/1.1" 500 291 "http://kong:8000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
```

**Comment by alexandre-vasc** [comment]
PR #4 fix this issue.
In this PR, if a configuration is not defined a default value will be used.
